server:
  port: 8080

spring:
  application:
    name: prices-service
  datasource:
    url: jdbc:h2:mem:pricesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: embedded
  h2:
    console:
      enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    root: INFO
    '[com.bcnc.pricing.infrastructure.adapter.out.persistence]': DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{requestId}] %logger{36} - %msg%n"